class SprintWorker
  include Sidekiq::Worker

  def perform(cron)
    Sprint.create!(
      iteration_id: "#{SecureRandom.alphanumeric(10)}",
      name: "autogenerated sprints",
      description: "'#{cron}' - '#{Time.current}'",
      member_data: {some: "data"},
      start_time: Time.current,
      end_time: Time.current + 2.weeks
    )
  end
end
