class SprintWorker
  include Sidekiq::Worker

  def perform(cron)
    Sprint.create!(
      iteration_id: "#{SecureRandom.alphanumeric(10)}",
      name: "autogenerated sprints",
      description: "'#{cron}' - '#{Time.current}'"
    )
  end
end
